# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - modules/cloudrun/main.tf
resources:
 pipelines:
   - pipeline: "Backend_app"
     source: "piyushkg007.Backend_app"
     trigger: true
    
   - pipeline: "Frontend_app"
     source: "piyushkg007.Frontend_app"
     trigger: true

pool: default
  

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- script: |
    terraform init  
    terraform validate  

  displayName: 'for init'

- script: |
    terraform plan  
     

  displayName: 'for plan'

- script: |
    terraform apply -auto-approve  
      

  displayName: 'for init'


